:sparkles: First implementation of the Sound component.
Tugduoff/RType pull request #112
Opened 2024-10-29 20:52 UTC by Tugduoff

For now its quite customizable. Indeed, you can do whatever you think you want to do with it (for the main game)...

Here is an example of a config : 

`{
                name = "Sound",
                args = {
                    sounds = (
                        {
                            id = "ATTACK",
                            path = "./assets/laser2.wav",
                            volume = 100,
                            pitch = 1,
                            loop = false
                        },
                        {
                            id = "HIT",
                            path = "./assets/hit.wav",
                            volume = 100,
                            pitch = 1,
                            loop = false
                        }
                    )
                }
            }`
            
In order to do that, ive created a nw component : Sound,
A new sfml component : SfmlSound,
And added handlers in thoses systems : 
Collision, Attack, Input, Config.

For any questions, feel free to ask !

2024-10-30 14:40 UTC, tibaudlemaout approved these changes
All seems good to me :+1:

2024-10-31 12:53 UTC, C0Florent submitted a review, later dismissed

2024-11-03 02:17 UTC, Tholarr requested changes

2024-11-03 02:17 UTC, Tholarr commented on plugins/systems/sfml/SpriteComponent.hpp
>                  // std::cerr << "INIT END for action: " << currentTexture.getAction() << std::endl;
error display commented on purpose ?

2024-11-03 02:27 UTC, Tugduoff commented on plugins/systems/sfml/SpriteComponent.hpp
>                  // std::cerr << "INIT END for action: " << currentTexture.getAction() << std::endl;
All good, deleted

2024-11-03 02:28 UTC, C0Florent approved these changes

2024-11-03 02:32 UTC, Tholarr approved these changes

2024-11-03 02:37 UTC, merged