:sparkles: Create SparseArray zipper
Tugduoff/RType pull request #99
Opened 2024-10-16 01:07 UTC by C0Florent

This PR finally implements the long-awaited `Zipper` class as a utility in our ECS.

## Features: a *Zipper*?

A zipper a utility that combines several iterators into a single iterator containing multiple elements.

The zipper implemented by this PR is actually a bit more than that: it combines several iterators of potentially empty values, into an iterator over groups of elements which are all non-empty at each index.

## What's the use for the R-Type?

To give a more concrete example: this could simplify the implementation of our `Move` system: in this case, we will construct a `Zipper` instance with both `SparseArray`s of Position and Velocity components, which allows us to use a ranged-base for loop, which will loop over entities which have both a position and a velocity, automatically skipping any entity that is missing either of these components.

## `IndexedZipper`

This PR also provides an `IndexedZipper`: the only difference between this and the `Zipper` is that its iterator's tuple contains the id of the entity alongside with the components instances.

I managed to avoid code duplication in Zipper.hpp and IndexedZipper.hpp by creating a GenericZipper.hpp, but unfortunately I was unable to avoid duplication between ZipperIterator and IndexedZipperIterator, so the files are almost identical.

## Side notes

I'm intentionnally leaving the refactor of our systems to use the Zipper to be done in a future PR since this already enough code to review.

I will later try to implement a `MapZipper` which could allow us to use an `std::map` to store components in the `SparseArray`

Both zippers are unit-tested! Yay!

2024-10-16 08:44 UTC, tibaudlemaout submitted a review, later dismissed
Must admit I don't understand every detail but it all seems good :+1:

2024-10-16 14:29 UTC, Tugduoff requested changes
The whole code looks correct and the addition of tests :test_tube: is very appreciable.
Now, as i mentioned in my review, a lot of the code is lacking documentation. It would be great to add that before merging this branch in order to have a clean and well documented code.

Good job on this Generic Zipper ;)

2024-10-16 14:29 UTC, Tugduoff commented on src/ECS/utilities/Zipper/GenericZipper.hpp
> +class GenericZipper {
Could you add a doxygen comment for this class ? 

For a class, you can add the @class keyword with the name of the class and a @brief description resuming the main goal.

2024-10-16 14:29 UTC, Tugduoff commented on src/ECS/utilities/Zipper/IndexedZipper.hpp
> +class IndexedZipper : public GenericZipper<
Same as for the generic Zipper class, could you add a doxygen comment to this class ?

2024-10-16 14:29 UTC, Tugduoff commented on src/ECS/utilities/Zipper/IndexedZipperIterator.hpp
This whole files seems to be lacking comments. Even for operators, don't forget that it might not be that usefull for us, but when reading the doxygen documentation, having a function without details about what it does is useless.

2024-10-16 14:29 UTC, Tugduoff commented on src/ECS/utilities/Zipper/IndexedZipperIterator.hpp
This works for classes, namespaces as well as functions and sometimes enums...

2024-10-21 13:35 UTC, Tugduoff approved these changes
:+1:

2024-10-21 15:35 UTC, ClementBaziret commented on tests/Makefile
There shouldn't be a Makefile in our project anymore.
Could you try to use CMake?
I think you could just list the tests source files and link criterion to it like any other libraries.

2024-10-21 15:35 UTC, ClementBaziret commented on tests/Zipper
What is this file for?

2024-10-21 15:37 UTC, ClementBaziret commented on tests/oneBin.mk
Same as the Makefile

2024-10-21 15:39 UTC, ClementBaziret requested changes
I don't understand a lot that have been made but it seems good 🫡
Just some changes about tests compilation but otherwise all good

2024-10-21 15:40 UTC, C0Florent commented on tests/Zipper
I think it's a symlink, which simplifies the paths in the test files

2024-10-21 16:22 UTC, C0Florent commented on tests/Makefile
Of course, I just wanted to be able to run tests myself, but using CMake is obviouly better. I'll look into it

2024-10-21 17:25 UTC, C0Florent commented on tests/Makefile
Done! I added A CMakeLists.txt which builds the unit tests

Do you think we should also add some shell scripts to wrap CMake (similar to the build_rtype.sh)?
And perhaps we could add unit tests run in our CI workflow

2024-10-22 16:15 UTC, ClementBaziret commented on tests/Makefile
We could you're right but we can see that later

2024-10-22 16:16 UTC, ClementBaziret approved these changes
Seems good to me :saluting_face:

2024-10-22 21:35 UTC, Tugduoff approved these changes

2024-10-23 06:27 UTC, merged